# SwiftLint configuration for Advent of Code repository
# Follows similar philosophy to golangci-lint: comprehensive but practical

# Exclude build artifacts and dependencies
excluded:
  - .build
  - .swiftpm
  - "**/Package.swift"

# Opt-in rules (disabled by default but we want them)
opt_in_rules:
  - empty_count              # Prefer isEmpty over count == 0
  - empty_string             # Prefer isEmpty over == ""
  - explicit_init            # Avoid explicit .init() calls
  - first_where              # Prefer .first(where:) over .filter { }.first
  - redundant_nil_coalescing # Remove unnecessary ?? nil
  - redundant_type_annotation # Avoid redundant type annotations
  - unused_optional_binding  # Remove unused let/var in bindings
  - vertical_whitespace_closing_braces # Limit vertical whitespace
  - vertical_whitespace_opening_braces # Limit vertical whitespace

# Disabled rules
disabled_rules:
  - todo                     # Allow TODOs in incomplete solutions
  - function_parameter_count # Some AoC problems need many parameters
  - nesting                  # Competitive programming style may nest deeply
  - file_name                # Solution.swift doesn't match Day00/Day01 struct names
  - implicit_return          # Explicit returns are clearer in AoC solutions
  - force_unwrapping         # Warn about force unwraps (configured below)

# Line length configuration
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

# Function body length - relaxed for AoC solutions
function_body_length:
  warning: 50
  error: 100

# Cyclomatic complexity - relaxed for puzzle solving
cyclomatic_complexity:
  warning: 15
  error: 25

# File length
file_length:
  warning: 500
  error: 1000

# Type body length
type_body_length:
  warning: 300
  error: 500

# Identifier naming
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - i
    - j
    - k
    - x
    - y
    - z
    - id
    - a
    - b

# Type naming
type_name:
  min_length: 2
  max_length: 50

# Custom rules for specific file patterns
custom_rules:
  no_print_in_utilities:
    name: "No print statements in utility files"
    regex: 'print\('
    match_kinds:
      - identifier
    included: ".*AOCUtilities/.*\\.swift"
    excluded: ".*InteractiveRunner\\.swift"
    message: "Utility files should not contain print statements"
    severity: warning

# File-specific rule exclusions
# Solution files get relaxed rules (similar to Go's \d+/main.go exclusions)
force_unwrapping:
  severity: warning

force_cast:
  severity: warning

# These rules are relaxed for solution files via command-line usage or
# by accepting warnings. Keep strict for AOCUtilities and AOCTestSupport.
